/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sumanumeros;

import javax.swing.JOptionPane;

/**
 * Ejercicio Calculadora de solo Sumas
 *
 * @author Pedro Daniel Pérez Sánchez DAM2 Vespertino
 */
public class SumaNumeros extends javax.swing.JFrame {

    /**
     * Creates new form SumaNumeros
     */
    public SumaNumeros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelPrimerNumero = new javax.swing.JLabel();
        jLabelSegundoNumero = new javax.swing.JLabel();
        jLabelResultado = new javax.swing.JLabel();
        jTextFieldPrimerNumero = new javax.swing.JTextField();
        jTextFieldSegundoNumero = new javax.swing.JTextField();
        jTextFieldTercerNumero = new javax.swing.JTextField();
        jButtonSumar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sumando"));

        jLabelPrimerNumero.setText("Primer Numero: ");

        jLabelSegundoNumero.setText("Segundo Numero:");

        jLabelResultado.setText("Resultado:");

        jTextFieldPrimerNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrimerNumeroActionPerformed(evt);
            }
        });
        jTextFieldPrimerNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPrimerNumeroKeyReleased(evt);
            }
        });

        jTextFieldSegundoNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSegundoNumeroActionPerformed(evt);
            }
        });
        jTextFieldSegundoNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSegundoNumeroKeyReleased(evt);
            }
        });

        jTextFieldTercerNumero.setEditable(false);
        jTextFieldTercerNumero.setEnabled(false);
        jTextFieldTercerNumero.setFocusable(false);
        jTextFieldTercerNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTercerNumeroActionPerformed(evt);
            }
        });

        jButtonSumar.setText("Sumar");
        jButtonSumar.setEnabled(false);
        jButtonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumarActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelResultado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelSegundoNumero, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPrimerNumero, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldPrimerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTercerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSegundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrimerNumero)
                    .addComponent(jTextFieldPrimerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSegundoNumero)
                    .addComponent(jTextFieldSegundoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelResultado)
                    .addComponent(jTextFieldTercerNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSumar)
                    .addComponent(jButtonBorrar))
                .addContainerGap())
        );

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jButtonSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPrimerNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrimerNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrimerNumeroActionPerformed

    private void jTextFieldTercerNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTercerNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTercerNumeroActionPerformed

    private void jTextFieldSegundoNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSegundoNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSegundoNumeroActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // Boton Salir
        System.exit(0);
        setDefaultCloseOperation(SumaNumeros.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        // Boton borrar
        jTextFieldPrimerNumero.setText("");
        jTextFieldSegundoNumero.setText("");
        jTextFieldTercerNumero.setText("");
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jTextFieldPrimerNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrimerNumeroKeyReleased
        // Campo Primer Numero
        if (isFloat(jTextFieldPrimerNumero.getText())) {//Compruebo si es entero
            jButtonSumar.setEnabled(true);
        }else{//Si no es un numero entero, borramos el valor introducido
            jTextFieldPrimerNumero.setText("");
            jButtonSumar.setEnabled(false);
        }

        //Compruebo si es ambos campos estan vacios
        if("".equals(jTextFieldPrimerNumero.getText())||"".equals(jTextFieldSegundoNumero.getText())){ 
            jButtonSumar.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldPrimerNumeroKeyReleased

    private void jTextFieldSegundoNumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSegundoNumeroKeyReleased
        // Campo Segundo Numero
        if (isFloat(jTextFieldSegundoNumero.getText())) {//Compruebo si es entero
            jButtonSumar.setEnabled(true);
        }else{//Si no es un numero entero, borramos el valor introducido
            jTextFieldSegundoNumero.setText("");
            jButtonSumar.setEnabled(false);
        }

        //Compruebo si es ambos campos estan vacios
        if("".equals(jTextFieldPrimerNumero.getText())||"".equals(jTextFieldSegundoNumero.getText())){
            jButtonSumar.setEnabled(false);
        }
    }//GEN-LAST:event_jTextFieldSegundoNumeroKeyReleased

    private void jButtonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumarActionPerformed
        // Codigo principal del Boton
        float resultado = 0;
        if (isFloat(jTextFieldPrimerNumero.getText())&&isFloat(jTextFieldSegundoNumero.getText())) {
            resultado = Float.parseFloat(jTextFieldPrimerNumero.getText())+Float.parseFloat(jTextFieldSegundoNumero.getText());
            jTextFieldTercerNumero.setText(String.format("%2.2f", resultado));
        }
    }//GEN-LAST:event_jButtonSumarActionPerformed

    
    /**
     * Metodo Auxiliar usado por los campos JText para comprobar el texto que tienen dentro
     * 
     * @param numero
     * @return 
     */
    public boolean isFloat(String numero){
        try{
            Float.parseFloat(numero);
            return true;
        }catch(NumberFormatException e){
            return false;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Fallo al Calcular: "+e.getMessage());
        }
        return false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SumaNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SumaNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SumaNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SumaNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SumaNumeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSumar;
    private javax.swing.JLabel jLabelPrimerNumero;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JLabel jLabelSegundoNumero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldPrimerNumero;
    private javax.swing.JTextField jTextFieldSegundoNumero;
    private javax.swing.JTextField jTextFieldTercerNumero;
    // End of variables declaration//GEN-END:variables
}
